---
debug: false
logs:
  level: DEBUG
  token: ~
mongodb:
  port: 27020
  database: catalog_staging
  host: catalog.sd2e.org
  username: catalog
  password: ~
storagesystems:
  data-sd2e-community:
    posix_path: /work/projects/SD2E-Community/prod/data
only_extant_files: False
downloaded: downloaded.json
