---
debug: false
logs:
  level: DEBUG
  token: ~
mongodb:
  # host: 127.0.0.1
  # username: catalog
  # password: catalog
  port: 27020
  database: catalog_dev
  host: data-catalog.sd2e.org
  username: catalog
  password: ~
storagesystems:
  data-sd2e-community:
    posix_path: /work/projects/SD2E-Community/prod/data
only_extant_files: False
downloaded: downloaded.json
